(deftheme zenburn-chap
  "Created 2013-08-13.")

(custom-theme-set-variables
 'zenburn-chap
 '(ansi-color-names-vector ["#3F3F3F" "#CC9393" "#7F9F7F" "#F0DFAF" "#8CD0D3" "#DC8CC3" "#93E0E3" "#DCDCCC"]))

(custom-theme-set-faces
 'zenburn-chap
 '(cursor ((t (:foreground "#DCDCCC" :background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#F0DFAF" :bold t))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(highlight ((t (:background "dark blue"))))
 '(region ((t (:background "DarkSlateGray4"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(font-lock-builtin-face ((t (:foreground "#DCDCCC" :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7F9F7F" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:foreground "#D0BF8F" :weight bold))))
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(header-line ((t (:foreground "#F0DFAF" :background "#2B2B2B" :box (:line-width -1 :style released-button)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#8FB28F" :background "#2B2B2B" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-buffer-id ((t (:foreground "#F0DFAF" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#5F7F5F" :background "#383838" :box (:line-width -1 :style released-button)))))
 '(isearch ((t (:foreground "#D0BF8F" :weight bold :background "#2B2B2B"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:foreground "#D0BF8F" :weight bold :background "#383838"))))
 '(match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(success ((t (:foreground "#7F9F7F" :weight bold))))
 '(warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(compilation-column-face ((t (:foreground "#F0DFAF"))))
 '(compilation-enter-directory-face ((t (:foreground "#7F9F7F"))))
 '(compilation-error-face ((t (:foreground "#BC8383" :weight bold :underline t))))
 '(compilation-face ((t (:foreground "#DCDCCC"))))
 '(compilation-info-face ((t (:foreground "#8CD0D3"))))
 '(compilation-info ((t (:foreground "#BFEBBF" :underline t))))
 '(compilation-leave-directory-face ((t (:foreground "#7F9F7F"))))
 '(compilation-line-face ((t (:foreground "#F0DFAF"))))
 '(compilation-line-number ((t (:foreground "#F0DFAF"))))
 '(compilation-message-face ((t (:foreground "#8CD0D3"))))
 '(compilation-warning-face ((t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(compilation-mode-line-exit ((t (:foreground "#9FC59F" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#CC9393" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#F0DFAF" :weight bold))))
 '(grep-context-face ((t (:foreground "#DCDCCC"))))
 '(grep-error-face ((t (:foreground "#BC8383" :weight bold :underline t))))
 '(grep-hit-face ((t (:foreground "#8CD0D3"))))
 '(grep-match-face ((t (:foreground "#DFAF8F" :weight bold))))
 '(menu ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(newsticker-date-face ((t (:foreground "#DCDCCC"))))
 '(newsticker-default-face ((t (:foreground "#DCDCCC"))))
 '(newsticker-enclosure-face ((t (:foreground "#AFD8AF"))))
 '(newsticker-extra-face ((t (:foreground "#5F5F5F" :height 0.8))))
 '(newsticker-feed-face ((t (:foreground "#DCDCCC"))))
 '(newsticker-immortal-item-face ((t (:foreground "#7F9F7F"))))
 '(newsticker-new-item-face ((t (:foreground "#8CD0D3"))))
 '(newsticker-obsolete-item-face ((t (:foreground "#CC9393"))))
 '(newsticker-old-item-face ((t (:foreground "#6F6F6F"))))
 '(newsticker-statistics-face ((t (:foreground "#DCDCCC"))))
 '(newsticker-treeview-face ((t (:foreground "#DCDCCC"))))
 '(newsticker-treeview-immortal-face ((t (:foreground "#7F9F7F"))))
 '(newsticker-treeview-listwindow-face ((t (:foreground "#DCDCCC"))))
 '(newsticker-treeview-new-face ((t (:foreground "#8CD0D3" :weight bold))))
 '(newsticker-treeview-obsolete-face ((t (:foreground "#CC9393"))))
 '(newsticker-treeview-old-face ((t (:foreground "#6F6F6F"))))
 '(newsticker-treeview-selection-face ((t (:foreground "#F0DFAF"))))
 '(ace-jump-face-background ((t (:foreground "#656555" :background "#3F3F3F" :inverse-video nil))))
 '(ace-jump-face-foreground ((t (:foreground "#9FC59F" :background "#3F3F3F" :inverse-video nil))))
 '(ack-separator ((t (:foreground "#DCDCCC"))))
 '(ack-file ((t (:foreground "#8CD0D3"))))
 '(ack-line ((t (:foreground "#F0DFAF"))))
 '(ack-match ((t (:foreground "#DFAF8F" :background "#2B2B2B" :weight bold))))
 '(font-latex-bold ((t (:inherit bold))))
 '(font-latex-warning ((t (:inherit font-lock-warning))))
 '(font-latex-sedate ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-latex-title-4 ((t (:inherit variable-pitch :weight bold))))
 '(ac-candidate-face ((t (:background "#6F6F6F" :foreground "black"))))
 '(ac-selection-face ((t (:background "#4C7073" :foreground "#DCDCCC"))))
 '(popup-tip-face ((t (:background "#D0BF8F" :foreground "black"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#366060"))))
 '(popup-scroll-bar-background-face ((t (:background "#2B2B2B"))))
 '(popup-isearch-match ((t (:background "#3F3F3F" :foreground "#DCDCCC"))))
 '(android-mode-debug-face ((t (:foreground "#8FB28F"))))
 '(android-mode-error-face ((t (:foreground "#DFAF8F" :weight bold))))
 '(android-mode-info-face ((t (:foreground "#DCDCCC"))))
 '(android-mode-verbose-face ((t (:foreground "#7F9F7F"))))
 '(android-mode-warning-face ((t (:foreground "#F0DFAF"))))
 '(bm-face ((t (:background "#E0CF9F" :foreground "#3F3F3F"))))
 '(bm-fringe-face ((t (:background "#E0CF9F" :foreground "#3F3F3F"))))
 '(bm-fringe-persistent-face ((t (:background "#5F7F5F" :foreground "#3F3F3F"))))
 '(bm-persistent-face ((t (:background "#5F7F5F" :foreground "#3F3F3F"))))
 '(clojure-test-failure-face ((t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(clojure-test-error-face ((t (:foreground "#CC9393" :weight bold :underline t))))
 '(clojure-test-success-face ((t (:foreground "#8FB28F" :weight bold :underline t))))
 '(ctbl:face-cell-select ((t (:background "#8CD0D3" :foreground "#3F3F3F"))))
 '(ctbl:face-continue-bar ((t (:background "#383838" :foreground "#3F3F3F"))))
 '(ctbl:face-row-select ((t (:background "#93E0E3" :foreground "#3F3F3F"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#BFEBBF" :background nil)) (t (:foreground "#5F7F5F" :background nil))))
 '(diff-changed ((t (:foreground "#F0DFAF"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#CC9393" :background nil)) (t (:foreground "#9C6363" :background nil))))
 '(diff-refine-added ((t :inherit diff-added :weight bold)))
 '(diff-refine-change ((t :inherit diff-changed :weight bold)))
 '(diff-refine-removed ((t :inherit diff-removed :weight bold)))
 '(diff-header ((((class color) (min-colors 89)) (:background "#5F5F5F")) (t (:background "#DCDCCC" :foreground "#3F3F3F"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#5F5F5F" :foreground "#DCDCCC" :bold t)) (t (:background "#DCDCCC" :foreground "#3F3F3F" :bold t))))
 '(diredp-display-msg ((t (:foreground "#8CD0D3"))))
 '(diredp-compressed-file-suffix ((t (:foreground "#DFAF8F"))))
 '(diredp-date-time ((t (:foreground "#DC8CC3"))))
 '(diredp-deletion ((t (:foreground "#F0DFAF"))))
 '(diredp-deletion-file-name ((t (:foreground "#CC9393"))))
 '(diredp-dir-heading ((t (:foreground "#8CD0D3" :background "#2B2B2B"))))
 '(diredp-dir-priv ((t (:foreground "#93E0E3"))))
 '(diredp-exec-priv ((t (:foreground "#CC9393"))))
 '(diredp-executable-tag ((t (:foreground "#8FB28F"))))
 '(diredp-file-name ((t (:foreground "#8CD0D3"))))
 '(diredp-file-suffix ((t (:foreground "#7F9F7F"))))
 '(diredp-flag-mark ((t (:foreground "#F0DFAF"))))
 '(diredp-flag-mark-line ((t (:foreground "#DFAF8F"))))
 '(diredp-ignored-file-name ((t (:foreground "#CC9393"))))
 '(diredp-link-priv ((t (:foreground "#F0DFAF"))))
 '(diredp-mode-line-flagged ((t (:foreground "#F0DFAF"))))
 '(diredp-mode-line-marked ((t (:foreground "#DFAF8F"))))
 '(diredp-no-priv ((t (:foreground "#DCDCCC"))))
 '(diredp-number ((t (:foreground "#8FB28F"))))
 '(diredp-other-priv ((t (:foreground "#E0CF9F"))))
 '(diredp-rare-priv ((t (:foreground "#BC8383"))))
 '(diredp-read-priv ((t (:foreground "#5F7F5F"))))
 '(diredp-symlink ((t (:foreground "#F0DFAF"))))
 '(diredp-write-priv ((t (:foreground "#DC8CC3"))))
 '(ert-test-result-expected ((t (:foreground "#BFEBBF" :background "#3F3F3F"))))
 '(ert-test-result-unexpected ((t (:foreground "#CC9393" :background "#3F3F3F"))))
 '(eshell-prompt ((t (:foreground "#F0DFAF" :weight bold))))
 '(eshell-ls-archive ((t (:foreground "#BC8383" :weight bold))))
 '(eshell-ls-backup ((t (:inherit font-lock-comment))))
 '(eshell-ls-clutter ((t (:inherit font-lock-comment))))
 '(eshell-ls-directory ((t (:foreground "#94BFF3" :weight bold))))
 '(eshell-ls-executable ((t (:foreground "#DCA3A3" :weight bold))))
 '(eshell-ls-unreadable ((t (:foreground "#DCDCCC"))))
 '(eshell-ls-missing ((t (:inherit font-lock-warning))))
 '(eshell-ls-product ((t (:inherit font-lock-doc))))
 '(eshell-ls-special ((t (:foreground "#F0DFAF" :weight bold))))
 '(eshell-ls-symlink ((t (:foreground "#93E0E3" :weight bold))))
 '(flx-highlight-face ((t (:foreground "#9FC59F" :weight bold))))
 '(flycheck-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC9393") :inherit unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#DFAF8F") :inherit unspecified)) (t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(flycheck-fringe-error ((t (:foreground "#BC8383" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(flymake-errline ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC9393") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave))) (:underline (:style wave :color "#DFAF8F") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(flymake-infoline ((((supports :underline (:style wave))) (:underline (:style wave :color "#7F9F7F") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#5F7F5F" :weight bold :underline t))))
 '(flyspell-duplicate ((((supports :underline (:style wave))) (:underline (:style wave :color "#DFAF8F") :inherit unspecified)) (t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC9393") :inherit unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(erc-action-face ((t (:inherit erc-default-face))))
 '(erc-bold-face ((t (:weight bold))))
 '(erc-current-nick-face ((t (:foreground "#8CD0D3" :weight bold))))
 '(erc-dangerous-host-face ((t (:inherit font-lock-warning))))
 '(erc-default-face ((t (:foreground "#DCDCCC"))))
 '(erc-direct-msg-face ((t (:inherit erc-default))))
 '(erc-error-face ((t (:inherit font-lock-warning))))
 '(erc-fool-face ((t (:inherit erc-default))))
 '(erc-highlight-face ((t (:inherit hover-highlight))))
 '(erc-input-face ((t (:foreground "#F0DFAF"))))
 '(erc-keyword-face ((t (:foreground "#8CD0D3" :weight bold))))
 '(erc-nick-default-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(erc-my-nick-face ((t (:foreground "#CC9393" :weight bold))))
 '(erc-nick-msg-face ((t (:inherit erc-default))))
 '(erc-notice-face ((t (:foreground "#7F9F7F"))))
 '(erc-pal-face ((t (:foreground "#DFAF8F" :weight bold))))
 '(erc-prompt-face ((t (:foreground "#DFAF8F" :background "#3F3F3F" :weight bold))))
 '(erc-timestamp-face ((t (:foreground "#8FB28F"))))
 '(erc-underline-face ((t (:underline t))))
 '(git-gutter:added ((t (:foreground "#7F9F7F" :weight bold :inverse-video t))))
 '(git-gutter:deleted ((t (:foreground "#CC9393" :weight bold :inverse-video t))))
 '(git-gutter:modified ((t (:foreground "#DC8CC3" :weight bold :inverse-video t))))
 '(git-gutter:unchanged ((t (:foreground "#DCDCCC" :weight bold :inverse-video t))))
 '(git-gutter-fr:added ((t (:foreground "#7F9F7F" :weight bold))))
 '(git-gutter-fr:deleted ((t (:foreground "#CC9393" :weight bold))))
 '(git-gutter-fr:modified ((t (:foreground "#DC8CC3" :weight bold))))
 '(gnus-group-mail-1 ((t (:bold t :inherit gnus-group-mail-1-empty))))
 '(gnus-group-mail-1-empty ((t (:inherit gnus-group-news-1-empty))))
 '(gnus-group-mail-2 ((t (:bold t :inherit gnus-group-mail-2-empty))))
 '(gnus-group-mail-2-empty ((t (:inherit gnus-group-news-2-empty))))
 '(gnus-group-mail-3 ((t (:bold t :inherit gnus-group-mail-3-empty))))
 '(gnus-group-mail-3-empty ((t (:inherit gnus-group-news-3-empty))))
 '(gnus-group-mail-4 ((t (:bold t :inherit gnus-group-mail-4-empty))))
 '(gnus-group-mail-4-empty ((t (:inherit gnus-group-news-4-empty))))
 '(gnus-group-mail-5 ((t (:bold t :inherit gnus-group-mail-5-empty))))
 '(gnus-group-mail-5-empty ((t (:inherit gnus-group-news-5-empty))))
 '(gnus-group-mail-6 ((t (:bold t :inherit gnus-group-mail-6-empty))))
 '(gnus-group-mail-6-empty ((t (:inherit gnus-group-news-6-empty))))
 '(gnus-group-mail-low ((t (:bold t :inherit gnus-group-mail-low-empty))))
 '(gnus-group-mail-low-empty ((t (:inherit gnus-group-news-low-empty))))
 '(gnus-group-news-1 ((t (:bold t :inherit gnus-group-news-1-empty))))
 '(gnus-group-news-2 ((t (:bold t :inherit gnus-group-news-2-empty))))
 '(gnus-group-news-3 ((t (:bold t :inherit gnus-group-news-3-empty))))
 '(gnus-group-news-4 ((t (:bold t :inherit gnus-group-news-4-empty))))
 '(gnus-group-news-5 ((t (:bold t :inherit gnus-group-news-5-empty))))
 '(gnus-group-news-6 ((t (:bold t :inherit gnus-group-news-6-empty))))
 '(gnus-group-news-low ((t (:bold t :inherit gnus-group-news-low-empty))))
 '(gnus-header-content ((t (:inherit message-header-other))))
 '(gnus-header-from ((t (:inherit message-header-from))))
 '(gnus-header-name ((t (:inherit message-header-name))))
 '(gnus-header-newsgroups ((t (:inherit message-header-other))))
 '(gnus-header-subject ((t (:inherit message-header-subject))))
 '(gnus-summary-cancelled ((t (:foreground "#DFAF8F"))))
 '(gnus-summary-high-ancient ((t (:foreground "#8CD0D3"))))
 '(gnus-summary-high-read ((t (:foreground "#7F9F7F" :weight bold))))
 '(gnus-summary-high-ticked ((t (:foreground "#DFAF8F" :weight bold))))
 '(gnus-summary-high-unread ((t (:foreground "#DCDCCC" :weight bold))))
 '(gnus-summary-low-ancient ((t (:foreground "#8CD0D3"))))
 '(gnus-summary-low-read ((t (:foreground "#7F9F7F"))))
 '(gnus-summary-low-ticked ((t (:foreground "#DFAF8F" :weight bold))))
 '(gnus-summary-low-unread ((t (:foreground "#DCDCCC"))))
 '(gnus-summary-normal-ancient ((t (:foreground "#8CD0D3"))))
 '(gnus-summary-normal-read ((t (:foreground "#7F9F7F"))))
 '(gnus-summary-normal-ticked ((t (:foreground "#DFAF8F" :weight bold))))
 '(gnus-summary-normal-unread ((t (:foreground "#DCDCCC"))))
 '(gnus-summary-selected ((t (:foreground "#F0DFAF" :weight bold))))
 '(gnus-cite-1 ((t (:foreground "#8CD0D3"))))
 '(gnus-cite-10 ((t (:foreground "#E0CF9F"))))
 '(gnus-cite-11 ((t (:foreground "#F0DFAF"))))
 '(gnus-cite-2 ((t (:foreground "#7CB8BB"))))
 '(gnus-cite-3 ((t (:foreground "#6CA0A3"))))
 '(gnus-cite-4 ((t (:foreground "#9FC59F"))))
 '(gnus-cite-5 ((t (:foreground "#8FB28F"))))
 '(gnus-cite-6 ((t (:foreground "#7F9F7F"))))
 '(gnus-cite-7 ((t (:foreground "#CC9393"))))
 '(gnus-cite-8 ((t (:foreground "#BC8383"))))
 '(gnus-cite-9 ((t (:foreground "#AC7373"))))
 '(gnus-group-news-1-empty ((t (:foreground "#F0DFAF"))))
 '(gnus-group-news-2-empty ((t (:foreground "#AFD8AF"))))
 '(gnus-group-news-3-empty ((t (:foreground "#8FB28F"))))
 '(gnus-group-news-4-empty ((t (:foreground "#6CA0A3"))))
 '(gnus-group-news-5-empty ((t (:foreground "#5C888B"))))
 '(gnus-group-news-6-empty ((t (:foreground "#5F5F5F"))))
 '(gnus-group-news-low-empty ((t (:foreground "#5F5F5F"))))
 '(gnus-signature ((t (:foreground "#F0DFAF"))))
 '(gnus-x ((t (:background "#DCDCCC" :foreground "#3F3F3F"))))
 '(guide-key/highlight-command-face ((t (:foreground "#8CD0D3"))))
 '(guide-key/key-face ((t (:foreground "#7F9F7F"))))
 '(guide-key/prefix-command-face ((t (:foreground "#8FB28F"))))
 '(helm-header ((t (:foreground "#7F9F7F" :background "#3F3F3F" :underline nil :box nil))))
 '(helm-source-header ((t (:foreground "#F0DFAF" :background "#2B2B2B" :underline nil :weight bold :box (:line-width -1 :style released-button)))))
 '(helm-selection ((t (:background "#4F4F4F" :underline nil))))
 '(helm-selection-line ((t (:background "#4F4F4F"))))
 '(helm-visible-mark ((t (:foreground "#3F3F3F" :background "#D0BF8F"))))
 '(helm-candidate-number ((t (:foreground "#BFEBBF" :background "#2B2B2B"))))
 '(helm-ff-directory ((t (:foreground "#DC8CC3"))))
 '(hl-line-face ((((class color) (min-colors 89)) (:background "#383838")) (t :weight bold)))
 '(hl-line ((((class color) (min-colors 89)) (:background "#383838")) (t :weight bold)))
 '(hl-sexp-face ((((class color) (min-colors 89)) (:background "#4F4F4F")) (t :weight bold)))
 '(ido-first-match ((t (:foreground "#F0DFAF" :weight bold))))
 '(ido-only-match ((t (:foreground "#DFAF8F" :weight bold))))
 '(ido-subdir ((t (:foreground "#F0DFAF"))))
 '(js2-warning ((t (:underline "#DFAF8F"))))
 '(js2-error ((t (:foreground "#CC9393" :weight bold))))
 '(js2-jsdoc-tag ((t (:foreground "#5F7F5F"))))
 '(js2-jsdoc-type ((t (:foreground "#9FC59F"))))
 '(js2-jsdoc-value ((t (:foreground "#AFD8AF"))))
 '(js2-function-param ((t (:foreground "#AFD8AF"))))
 '(js2-external-variable ((t (:foreground "#DFAF8F"))))
 '(jabber-roster-user-away ((t (:foreground "#9FC59F"))))
 '(jabber-roster-user-online ((t (:foreground "#7CB8BB"))))
 '(jabber-roster-user-dnd ((t (:foreground "#DCA3A3"))))
 '(jabber-rare-time-face ((t (:foreground "#8FB28F"))))
 '(jabber-chat-prompt-local ((t (:foreground "#7CB8BB"))))
 '(jabber-chat-prompt-foreign ((t (:foreground "#DCA3A3"))))
 '(jabber-activity-face ((t (:foreground "#DCA3A3"))))
 '(jabber-activity-personal-face ((t (:foreground "#94BFF3"))))
 '(jabber-title-small ((t (:height 1.1 :weight bold))))
 '(jabber-title-medium ((t (:height 1.2 :weight bold))))
 '(jabber-title-large ((t (:height 1.3 :weight bold))))
 '(linum ((t (:foreground "#9FC59F" :background "#3F3F3F"))))
 '(macrostep-gensym-1 ((t (:foreground "#9FC59F" :background "#2B2B2B"))))
 '(macrostep-gensym-2 ((t (:foreground "#DCA3A3" :background "#2B2B2B"))))
 '(macrostep-gensym-3 ((t (:foreground "#94BFF3" :background "#2B2B2B"))))
 '(macrostep-gensym-4 ((t (:foreground "#DC8CC3" :background "#2B2B2B"))))
 '(macrostep-gensym-5 ((t (:foreground "#F0DFAF" :background "#2B2B2B"))))
 '(macrostep-expansion-highlight-face ((t (:inherit highlight))))
 '(macrostep-macro-face ((t (:underline t))))
 '(magit-section-title ((t (:foreground "#F0DFAF" :weight bold))))
 '(magit-branch ((t (:foreground "#DFAF8F" :weight bold))))
 '(magit-item-highlight ((t (:background "#4F4F4F" :bold nil))))
 '(egg-text-base ((t (:foreground "#DCDCCC"))))
 '(egg-help-header-1 ((t (:foreground "#F0DFAF"))))
 '(egg-help-header-2 ((t (:foreground "#AFD8AF"))))
 '(egg-branch ((t (:foreground "#F0DFAF"))))
 '(egg-branch-mono ((t (:foreground "#F0DFAF"))))
 '(egg-term ((t (:foreground "#F0DFAF"))))
 '(egg-diff-add ((t (:foreground "#BFEBBF"))))
 '(egg-diff-del ((t (:foreground "#DCA3A3"))))
 '(egg-diff-file-header ((t (:foreground "#D0BF8F"))))
 '(egg-section-title ((t (:foreground "#F0DFAF"))))
 '(egg-stash-mono ((t (:foreground "#BFEBBF"))))
 '(message-cited-text ((t (:inherit font-lock-comment))))
 '(message-header-name ((t (:foreground "#8FB28F"))))
 '(message-header-other ((t (:foreground "#7F9F7F"))))
 '(message-header-to ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-from ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-cc ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-newsgroups ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-subject ((t (:foreground "#DFAF8F" :weight bold))))
 '(message-header-xheader ((t (:foreground "#7F9F7F"))))
 '(message-mml ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-separator ((t (:inherit font-lock-comment))))
 '(mew-face-header-subject ((t (:foreground "#DFAF8F"))))
 '(mew-face-header-from ((t (:foreground "#F0DFAF"))))
 '(mew-face-header-date ((t (:foreground "#7F9F7F"))))
 '(mew-face-header-to ((t (:foreground "#CC9393"))))
 '(mew-face-header-key ((t (:foreground "#7F9F7F"))))
 '(mew-face-header-private ((t (:foreground "#7F9F7F"))))
 '(mew-face-header-important ((t (:foreground "#8CD0D3"))))
 '(mew-face-header-marginal ((t (:foreground "#DCDCCC" :weight bold))))
 '(mew-face-header-warning ((t (:foreground "#CC9393"))))
 '(mew-face-header-xmew ((t (:foreground "#7F9F7F"))))
 '(mew-face-header-xmew-bad ((t (:foreground "#CC9393"))))
 '(mew-face-body-url ((t (:foreground "#DFAF8F"))))
 '(mew-face-body-comment ((t (:foreground "#DCDCCC" :slant italic))))
 '(mew-face-body-cite1 ((t (:foreground "#7F9F7F"))))
 '(mew-face-body-cite2 ((t (:foreground "#8CD0D3"))))
 '(mew-face-body-cite3 ((t (:foreground "#DFAF8F"))))
 '(mew-face-body-cite4 ((t (:foreground "#F0DFAF"))))
 '(mew-face-body-cite5 ((t (:foreground "#CC9393"))))
 '(mew-face-mark-review ((t (:foreground "#8CD0D3"))))
 '(mew-face-mark-escape ((t (:foreground "#7F9F7F"))))
 '(mew-face-mark-delete ((t (:foreground "#CC9393"))))
 '(mew-face-mark-unlink ((t (:foreground "#F0DFAF"))))
 '(mew-face-mark-refile ((t (:foreground "#7F9F7F"))))
 '(mew-face-mark-unread ((t (:foreground "#AC7373"))))
 '(mew-face-eof-message ((t (:foreground "#7F9F7F"))))
 '(mew-face-eof-part ((t (:foreground "#F0DFAF"))))
 '(paren-face-match ((t (:foreground "#93E0E3" :background "#3F3F3F" :weight bold))))
 '(paren-face-mismatch ((t (:foreground "#3F3F3F" :background "#DC8CC3" :weight bold))))
 '(paren-face-no-match ((t (:foreground "#3F3F3F" :background "#CC9393" :weight bold))))
 '(mingus-directory-face ((t (:foreground "#8CD0D3"))))
 '(mingus-pausing-face ((t (:foreground "#DC8CC3"))))
 '(mingus-playing-face ((t (:foreground "#93E0E3"))))
 '(mingus-playlist-face ((t (:foreground "#93E0E3"))))
 '(mingus-song-file-face ((t (:foreground "#F0DFAF"))))
 '(mingus-stopped-face ((t (:foreground "#CC9393"))))
 '(nav-face-heading ((t (:foreground "#F0DFAF"))))
 '(nav-face-button-num ((t (:foreground "#93E0E3"))))
 '(nav-face-dir ((t (:foreground "#7F9F7F"))))
 '(nav-face-hdir ((t (:foreground "#CC9393"))))
 '(nav-face-file ((t (:foreground "#DCDCCC"))))
 '(nav-face-hfile ((t (:foreground "#8C5353"))))
 '(mu4e-cited-1-face ((t (:foreground "#8CD0D3" :slant italic))))
 '(mu4e-cited-2-face ((t (:foreground "#9FC59F" :slant italic))))
 '(mu4e-cited-3-face ((t (:foreground "#6CA0A3" :slant italic))))
 '(mu4e-cited-4-face ((t (:foreground "#7F9F7F" :slant italic))))
 '(mu4e-cited-5-face ((t (:foreground "#4C7073" :slant italic))))
 '(mu4e-cited-6-face ((t (:foreground "#5F7F5F" :slant italic))))
 '(mu4e-cited-7-face ((t (:foreground "#8CD0D3" :slant italic))))
 '(mu4e-replied-face ((t (:foreground "#6F6F6F"))))
 '(mu4e-trashed-face ((t (:foreground "#6F6F6F" :strike-through t))))
 '(mumamo-background-chunk-major ((t (:background nil))))
 '(mumamo-background-chunk-submode1 ((t (:background "#2B2B2B"))))
 '(mumamo-background-chunk-submode2 ((t (:background "#5F5F5F"))))
 '(mumamo-background-chunk-submode3 ((t (:background "#6F6F6F"))))
 '(mumamo-background-chunk-submode4 ((t (:background "#4F4F4F"))))
 '(org-agenda-date-today ((t (:foreground "white" :slant italic :weight bold))))
 '(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 '(org-archived ((t (:foreground "#DCDCCC" :weight bold))))
 '(org-checkbox ((t (:background "#5F5F5F" :foreground "white" :box (:line-width 1 :style released-button)))))
 '(org-date ((t (:foreground "#8CD0D3" :underline t))))
 '(org-deadline-announce ((t (:foreground "#BC8383"))))
 '(org-done ((t (:bold t :weight bold :foreground "#AFD8AF"))))
 '(org-formula ((t (:foreground "#D0BF8F"))))
 '(org-headline-done ((t (:foreground "#AFD8AF"))))
 '(org-hide ((t (:foreground "#2B2B2B"))))
 '(org-level-1 ((t (:foreground "#DFAF8F"))))
 '(org-level-2 ((t (:foreground "#BFEBBF"))))
 '(org-level-3 ((t (:foreground "#7CB8BB"))))
 '(org-level-4 ((t (:foreground "#D0BF8F"))))
 '(org-level-5 ((t (:foreground "#93E0E3"))))
 '(org-level-6 ((t (:foreground "#9FC59F"))))
 '(org-level-7 ((t (:foreground "#8C5353"))))
 '(org-level-8 ((t (:foreground "#4C7073"))))
 '(org-link ((t (:foreground "#D0BF8F" :underline t))))
 '(org-scheduled ((t (:foreground "#BFEBBF"))))
 '(org-scheduled-previously ((t (:foreground "#8C5353"))))
 '(org-scheduled-today ((t (:foreground "#94BFF3"))))
 '(org-sexp-date ((t (:foreground "#94BFF3" :underline t))))
 '(org-special-keyword ((t (:foreground "#656555" :weight normal))))
 '(org-table ((t (:foreground "#9FC59F"))))
 '(org-tag ((t (:bold t :weight bold))))
 '(org-time-grid ((t (:foreground "#DFAF8F"))))
 '(org-todo ((t (:bold t :foreground "#CC9393" :weight bold))))
 '(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
 '(org-warning ((t (:bold t :foreground "#CC9393" :weight bold :underline nil))))
 '(org-column ((t (:background "#2B2B2B"))))
 '(org-column-title ((t (:background "#2B2B2B" :underline t :weight bold))))
 '(outline-1 ((t (:foreground "#DFAF8F"))))
 '(outline-2 ((t (:foreground "#BFEBBF"))))
 '(outline-3 ((t (:foreground "#7CB8BB"))))
 '(outline-4 ((t (:foreground "#D0BF8F"))))
 '(outline-5 ((t (:foreground "#93E0E3"))))
 '(outline-6 ((t (:foreground "#9FC59F"))))
 '(outline-7 ((t (:foreground "#8C5353"))))
 '(outline-8 ((t (:foreground "#4C7073"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#DCDCCC"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#9FC59F"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#D0BF8F"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#93E0E3"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#5F7F5F"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#94BFF3"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#E0CF9F"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#8FB28F"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#6CA0A3"))))
 '(rainbow-delimiters-depth-10-face ((t (:foreground "#DFAF8F"))))
 '(rainbow-delimiters-depth-11-face ((t (:foreground "#7F9F7F"))))
 '(rainbow-delimiters-depth-12-face ((t (:foreground "#366060"))))
 '(rcirc-my-nick ((t (:foreground "#8CD0D3"))))
 '(rcirc-other-nick ((t (:foreground "#DFAF8F"))))
 '(rcirc-bright-nick ((t (:foreground "#94BFF3"))))
 '(rcirc-dim-nick ((t (:foreground "#6CA0A3"))))
 '(rcirc-server ((t (:foreground "#7F9F7F"))))
 '(rcirc-server-prefix ((t (:foreground "#8FB28F"))))
 '(rcirc-timestamp ((t (:foreground "#9FC59F"))))
 '(rcirc-nick-in-message ((t (:foreground "#F0DFAF"))))
 '(rcirc-nick-in-message-full-line ((t (:bold t))))
 '(rcirc-prompt ((t (:foreground "#F0DFAF" :bold t))))
 '(rcirc-track-nick ((t (:inverse-video t))))
 '(rcirc-track-keyword ((t (:bold t))))
 '(rcirc-url ((t (:bold t))))
 '(rcirc-keyword ((t (:foreground "#F0DFAF" :bold t))))
 '(rpm-spec-dir-face ((t (:foreground "#7F9F7F"))))
 '(rpm-spec-doc-face ((t (:foreground "#7F9F7F"))))
 '(rpm-spec-ghost-face ((t (:foreground "#CC9393"))))
 '(rpm-spec-macro-face ((t (:foreground "#F0DFAF"))))
 '(rpm-spec-obsolete-tag-face ((t (:foreground "#CC9393"))))
 '(rpm-spec-package-face ((t (:foreground "#CC9393"))))
 '(rpm-spec-section-face ((t (:foreground "#F0DFAF"))))
 '(rpm-spec-tag-face ((t (:foreground "#8CD0D3"))))
 '(rpm-spec-var-face ((t (:foreground "#CC9393"))))
 '(rst-level-1-face ((t (:foreground "#DFAF8F"))))
 '(rst-level-2-face ((t (:foreground "#8FB28F"))))
 '(rst-level-3-face ((t (:foreground "#7CB8BB"))))
 '(rst-level-4-face ((t (:foreground "#D0BF8F"))))
 '(rst-level-5-face ((t (:foreground "#93E0E3"))))
 '(rst-level-6-face ((t (:foreground "#5F7F5F"))))
 '(show-paren-mismatch ((t (:foreground "#9C6363" :background "#3F3F3F" :weight bold))))
 '(show-paren-match ((t (:foreground "#7CB8BB" :background "#3F3F3F" :weight bold))))
 '(sml-modeline-end-face ((t :inherit default :width condensed)))
 '(slime-repl-inputed-output-face ((t (:foreground "#CC9393"))))
 '(tabbar-button ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(tabbar-selected ((t (:foreground "#DCDCCC" :background "#3F3F3F" :box (:line-width -1 :style pressed-button)))))
 '(tabbar-unselected ((t (:foreground "#DCDCCC" :background "#4F4F4F" :box (:line-width -1 :style released-button)))))
 '(term-color-black ((t (:foreground "#3F3F3F" :background "#2B2B2B"))))
 '(term-color-red ((t (:foreground "#AC7373" :background "#8C5353"))))
 '(term-color-green ((t (:foreground "#7F9F7F" :background "#9FC59F"))))
 '(term-color-yellow ((t (:foreground "#DFAF8F" :background "#F0DFAF"))))
 '(term-color-blue ((t (:foreground "#7CB8BB" :background "#4C7073"))))
 '(term-color-magenta ((t (:foreground "#DC8CC3" :background "#CC9393"))))
 '(term-color-cyan ((t (:foreground "#93E0E3" :background "#8CD0D3"))))
 '(term-color-white ((t (:foreground "#DCDCCC" :background "#656555"))))
 '(term-default-fg-color ((t (:inherit term-color-white))))
 '(term-default-bg-color ((t (:inherit term-color-black))))
 '(vhl/default-face ((t (:background "#383838"))))
 '(w3m-anchor ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(w3m-arrived-anchor ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(w3m-form ((t (:foreground "#BC8383" :underline t))))
 '(w3m-header-line-location-title ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(w3m-history-current-url ((t (:inherit match))))
 '(w3m-lnum ((t (:foreground "#9FC59F" :background "#3F3F3F"))))
 '(w3m-lnum-match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(w3m-lnum-minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(whitespace-space ((t (:background "#4F4F4F" :foreground "#4F4F4F"))))
 '(whitespace-hspace ((t (:background "#4F4F4F" :foreground "#4F4F4F"))))
 '(whitespace-tab ((t (:background "#BC8383"))))
 '(whitespace-newline ((t (:foreground "#4F4F4F"))))
 '(whitespace-trailing ((t (:background "#CC9393"))))
 '(whitespace-line ((t (:background "#3F3F3F" :foreground "#DC8CC3"))))
 '(whitespace-space-before-tab ((t (:background "#DFAF8F" :foreground "#DFAF8F"))))
 '(whitespace-indentation ((t (:background "#F0DFAF" :foreground "#CC9393"))))
 '(whitespace-empty ((t (:background "#F0DFAF"))))
 '(whitespace-space-after-tab ((t (:background "#F0DFAF" :foreground "#CC9393"))))
 '(wl-highlight-folder-few-face ((t (:foreground "#AC7373"))))
 '(wl-highlight-folder-many-face ((t (:foreground "#BC8383"))))
 '(wl-highlight-folder-path-face ((t (:foreground "#DFAF8F"))))
 '(wl-highlight-folder-unread-face ((t (:foreground "#8CD0D3"))))
 '(wl-highlight-folder-zero-face ((t (:foreground "#DCDCCC"))))
 '(wl-highlight-folder-unknown-face ((t (:foreground "#8CD0D3"))))
 '(wl-highlight-message-citation-header ((t (:foreground "#BC8383"))))
 '(wl-highlight-message-cited-text-1 ((t (:foreground "#CC9393"))))
 '(wl-highlight-message-cited-text-2 ((t (:foreground "#9FC59F"))))
 '(wl-highlight-message-cited-text-3 ((t (:foreground "#8CD0D3"))))
 '(wl-highlight-message-cited-text-4 ((t (:foreground "#94BFF3"))))
 '(wl-highlight-message-header-contents-face ((t (:foreground "#7F9F7F"))))
 '(wl-highlight-message-headers-face ((t (:foreground "#DCA3A3"))))
 '(wl-highlight-message-important-header-contents ((t (:foreground "#9FC59F"))))
 '(wl-highlight-message-header-contents ((t (:foreground "#8FB28F"))))
 '(wl-highlight-message-important-header-contents2 ((t (:foreground "#9FC59F"))))
 '(wl-highlight-message-signature ((t (:foreground "#7F9F7F"))))
 '(wl-highlight-message-unimportant-header-contents ((t (:foreground "#DCDCCC"))))
 '(wl-highlight-summary-answered-face ((t (:foreground "#8CD0D3"))))
 '(wl-highlight-summary-disposed-face ((t (:foreground "#DCDCCC" :slant italic))))
 '(wl-highlight-summary-new-face ((t (:foreground "#8CD0D3"))))
 '(wl-highlight-summary-normal-face ((t (:foreground "#DCDCCC"))))
 '(wl-highlight-summary-thread-top-face ((t (:foreground "#F0DFAF"))))
 '(wl-highlight-thread-indent-face ((t (:foreground "#DC8CC3"))))
 '(wl-highlight-summary-refiled-face ((t (:foreground "#DCDCCC"))))
 '(wl-highlight-summary-displaying-face ((t (:underline t :weight bold))))
 '(which-func ((t (:foreground "#BFEBBF"))))
 '(yascroll:thumb-text-area ((t (:background "#2B2B2B"))))
 '(yascroll:thumb-fringe ((t (:background "#2B2B2B" :foreground "#2B2B2B"))))
 '(default ((t (:background "gray20" :foreground "#DCDCCC")))))

(provide-theme 'zenburn-chap)
